package lspace.ns.vocab.schema
import lspace.ns.vocab.schema._
import lspace.Label.D._
import lspace.Label.P._
import lspace.structure.{Property => LProperty, PropertyDef}
object produces extends PropertyDef(
        iri = "http://schema.org/produces",
        iris = Set("http://schema.org/produces"),
        label = "produces",
        comment = """The tangible thing generated by the service, e.g. a passport, permit, etc.""",
        `@extends` = () => List(),
        `@range` = () => List(Thing.ontology)
       ){
}