package lspace.ns.vocab.schema
import lspace.ns.vocab.schema._
import lspace.Label.D._
import lspace.Label.P._
import lspace.structure.{Property, PropertyDef}
object serviceOutput
    extends PropertyDef(
      iri = "http://schema.org/serviceOutput",
      iris = Set("http://schema.org/serviceOutput"),
      label = "serviceOutput",
      comment = """The tangible thing generated by the service, e.g. a passport, permit, etc.""",
      `@extends` = () => List(),
      `@range` = () => List(Thing.ontology)
    ) {

  override lazy val properties: List[Property] = List()
  trait Properties
}
